n, m = map(int, input().split())
a = set(map(int, input().split()))
b = set(map(int, input().split()))
ans = list(a.intersection(b))
ans.sort()
print(*ans)
ans1 = list(a.difference(b))
ans1.sort()
ans2 = list(b.difference(a))
ans2.sort()
print(*ans1)
print(*ans2)